// Premium Theme Engine - All 8 Themes from the original app
export const THEMES = {
    cyber_nexus: {
        name: "Cyber Nexus",
        primary: "#00f5ff",
        secondary: "#7b61ff",
        accent: "#ff2a6d",
        background: "#0a0a1f",
        cardBg: "rgba(16, 18, 63, 0.9)",
        text: "#ffffff",
        textSecondary: "#b4b9ff",
        success: "#00ff9d",
        warning: "#ffcc00",
        error: "#ff2a6d",
    },
    deep_space: {
        name: "Deep Space",
        primary: "#8b5cf6",
        secondary: "#06b6d4",
        accent: "#f59e0b",
        background: "#030712",
        cardBg: "rgba(17, 24, 39, 0.9)",
        text: "#f8fafc",
        textSecondary: "#cbd5e1",
        success: "#10b981",
        warning: "#f59e0b",
        error: "#ef4444",
    },
    neon_dream: {
        name: "Neon Dream",
        primary: "#ff0080",
        secondary: "#00ffcc",
        accent: "#ffcc00",
        background: "#0a0014",
        cardBg: "rgba(42, 0, 56, 0.9)",
        text: "#ffffff",
        textSecondary: "#ff99e6",
        success: "#00ff88",
        warning: "#ffcc00",
        error: "#ff0066",
    },
    quantum_glass: {
        name: "Quantum Glass",
        primary: "#3b82f6",
        secondary: "#10b981",
        accent: "#f59e0b",
        background: "#0f172a",
        cardBg: "rgba(30, 41, 59, 0.9)",
        text: "#f1f5f9",
        textSecondary: "#94a3b8",
        success: "#10b981",
        warning: "#f59e0b",
        error: "#ef4444",
    },
    midnight_purple: {
        name: "Midnight Purple",
        primary: "#a855f7",
        secondary: "#ec4899",
        accent: "#f59e0b",
        background: "#0f0519",
        cardBg: "rgba(33, 16, 56, 0.9)",
        text: "#faf5ff",
        textSecondary: "#d8b4fe",
        success: "#10b981",
        warning: "#f59e0b",
        error: "#ef4444",
    },
    cyberpunk: {
        name: "Cyberpunk",
        primary: "#00ff9d",
        secondary: "#ff2a6d",
        accent: "#0055ff",
        background: "#001122",
        cardBg: "rgba(0, 34, 68, 0.9)",
        text: "#00ff9d",
        textSecondary: "#66ffcc",
        success: "#00ff9d",
        warning: "#ffcc00",
        error: "#ff2a6d",
    },
    sunset_oasis: {
        name: "Sunset Oasis",
        primary: "#ff6b35",
        secondary: "#ffa500",
        accent: "#00ced1",
        background: "#1a0f0f",
        cardBg: "rgba(42, 21, 21, 0.9)",
        text: "#fff5f5",
        textSecondary: "#ffd7ba",
        success: "#00ced1",
        warning: "#ffa500",
        error: "#ff6b35",
    },
    arctic_ice: {
        name: "Arctic Ice",
        primary: "#00b4d8",
        secondary: "#90e0ef",
        accent: "#ff9e00",
        background: "#001219",
        cardBg: "rgba(0, 42, 59, 0.9)",
        text: "#e9f5f9",
        textSecondary: "#a8dadc",
        success: "#90e0ef",
        warning: "#ff9e00",
        error: "#ff6b6b",
    },
};

export const getTheme = (themeName) => {
    return THEMES[themeName] || THEMES.cyber_nexus;
};

export const getThemeNames = () => {
    return Object.keys(THEMES);
};
